// <auto-generated />
using System;
using Capzlog.Mobile.DataAccess.DataSyncHistory;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capzlog.Mobile.DataAccess.DataSyncHistory.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class DataSyncHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Capzlog.Mobile.DataAccess.DataSyncHistory.Entities.MyEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MyEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
