// <auto-generated />
using DataAccess;
using DataAccess.MyDbContextCompiled;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(MyDbContext), typeof(MyDbContextModel))]
