// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using DataAccess.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DataAccess.MyDbContextCompiled
{
    public static class MyEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ID>k__BackingField")]
        public static extern ref Guid ID(MyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedTimestamp>k__BackingField")]
        public static extern ref DateTime CreatedTimestamp(MyEntity @this);
    }
}
